services:
  # Service Redis (Memori Cache & Queue)
  redis:
    image: redis:alpine
    container_name: arliva_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Service Mailpit 
  mailpit:
    image: axllent/mailpit:latest
    container_name: arliva_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025" # Port SMTP 
      - "8025:8025" # Port Web UI 

volumes:
  redis_data: